# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHUB'
    repository: 'aftab70/apache2'
    command: 'build'
    Dockerfile: '**/Dockerfile'
